spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: mdbuser
    password: '!mdb.gvbe6#'
    url: 'jdbc:mysql://172.27.106.55:3306/moment?characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false'
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

property:
  hello: default_hello
  hi: default_hi
  hey: default_hey

  
logging:
    level:
      com.example.demo: debug
      com.example.demo.controller: debug
      com.example.demo.user.service: debug
      

---
spring:
  profiles: local
  

property:
  hello: local_hello

---

spring:
  profiles: dev
    

property:
  hi: dev_hi

---

spring:
  profiles: production

property:
  hey: production_hey